# Data Analysis of the Depression dataset using Pandas

## Importing of libraries and Reading of dataset



In [1]:
#Importing of Libraries
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from datetime import datetime

In [2]:
#Uploading of csv to Google Colab
from google.colab import files
uploaded = files.upload()

Saving depression_dataset.csv to depression_dataset.csv


In [3]:
data = pd.read_csv('depression_dataset.csv')
data.head()

id  Gender   Age           City Profession  Academic Pressure  \
0   2    Male  33.0  Visakhapatnam    Student                5.0   
1   8  Female  24.0      Bangalore    Student                2.0   
2  26    Male  31.0       Srinagar    Student                3.0   
3  30  Female  28.0       Varanasi    Student                3.0   
4  32  Female  25.0         Jaipur    Student                4.0   

   Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0            0.0  8.97                 2.0               0.0   
1            0.0  5.90                 5.0               0.0   
2            0.0  7.03                 5.0               0.0   
3            0.0  5.59                 2.0               0.0   
4            0.0  8.13                 3.0               0.0   

        Sleep Duration Dietary Habits   Degree  \
0          '5-6 hours'        Healthy  B.Pharm   
1          '5-6 hours'       Moderate      BSc   
2  'Less than 5 hours'        Healthy       BA   
3          '7-8 hours'       Moderate      BCA   
4          '5-6 hours'       Moderate   M.Tech   

  Have you ever had suicidal thoughts ?  Work/Study Hours Financial Stress  \
0                                   Yes               3.0              1.0   
1                                    No               3.0              2.0   
2                                    No               9.0              1.0   
3                                   Yes               4.0              5.0   
4                                   Yes               1.0              1.0   

  Family History of Mental Illness  Depression  
0                               No           1  
1                              Yes           0  
2                              Yes           0  
3                              Yes           1  
4                               No           0

## Understanding of the dataset

In [4]:
data.shape

(27901, 18)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   id                                     27901 non-null  int64  
 1   Gender                                 27901 non-null  object 
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  object 
 4   Profession                             27901 non-null  object 
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  object 
 11  Di

In [6]:
#Presence of missing values
data.isnull().sum()

id                                       0
Gender                                   0
Age                                      0
City                                     0
Profession                               0
Academic Pressure                        0
Work Pressure                            0
CGPA                                     0
Study Satisfaction                       0
Job Satisfaction                         0
Sleep Duration                           0
Dietary Habits                           0
Degree                                   0
Have you ever had suicidal thoughts ?    0
Work/Study Hours                         0
Financial Stress                         0
Family History of Mental Illness         0
Depression                               0
dtype: int64

In [7]:
#Presence of duplicates
data.duplicated().sum()

np.int64(0)

In [8]:
data.columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='object')

In [9]:
data.rename(columns = {'Have you ever had suicidal thoughts ?': 'Suicidal thoughts', 'Family History of Mental Illness': 'Mental illness'},inplace = True)
data.head()

id  Gender   Age           City Profession  Academic Pressure  \
0   2    Male  33.0  Visakhapatnam    Student                5.0   
1   8  Female  24.0      Bangalore    Student                2.0   
2  26    Male  31.0       Srinagar    Student                3.0   
3  30  Female  28.0       Varanasi    Student                3.0   
4  32  Female  25.0         Jaipur    Student                4.0   

   Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0            0.0  8.97                 2.0               0.0   
1            0.0  5.90                 5.0               0.0   
2            0.0  7.03                 5.0               0.0   
3            0.0  5.59                 2.0               0.0   
4            0.0  8.13                 3.0               0.0   

        Sleep Duration Dietary Habits   Degree Suicidal thoughts  \
0          '5-6 hours'        Healthy  B.Pharm               Yes   
1          '5-6 hours'       Moderate      BSc                No   
2  'Less than 5 hours'        Healthy       BA                No   
3          '7-8 hours'       Moderate      BCA               Yes   
4          '5-6 hours'       Moderate   M.Tech               Yes   

   Work/Study Hours Financial Stress Mental illness  Depression  
0               3.0              1.0             No           1  
1               3.0              2.0            Yes           0  
2               9.0              1.0            Yes           0  
3               4.0              5.0            Yes           1  
4               1.0              1.0             No           0

In [10]:
data['Depression'].value_counts()

Depression
1    16336
0    11565
Name: count, dtype: int64

In [11]:
data['City'].unique()

array(['Visakhapatnam', 'Bangalore', 'Srinagar', 'Varanasi', 'Jaipur',
       'Pune', 'Thane', 'Chennai', 'Nagpur', 'Nashik', 'Vadodara',
       'Kalyan', 'Rajkot', 'Ahmedabad', 'Kolkata', 'Mumbai', 'Lucknow',
       'Indore', 'Surat', 'Ludhiana', 'Bhopal', 'Meerut', 'Agra',
       'Ghaziabad', 'Hyderabad', 'Vasai-Virar', 'Kanpur', 'Patna',
       'Faridabad', 'Delhi', 'Saanvi', 'M.Tech', 'Bhavna', "'Less Delhi'",
       'City', '3.0', "'Less than 5 Kalyan'", 'Mira', 'Harsha', 'Vaanya',
       'Gaurav', 'Harsh', 'Reyansh', 'Kibara', 'Rashi', 'ME', 'M.Com',
       'Nalyan', 'Mihir', 'Nalini', 'Nandini', 'Khaziabad'], dtype=object)

In [12]:
data['Profession'].unique()

array(['Student', "'Civil Engineer'", 'Architect', "'UX/UI Designer'",
       "'Digital Marketer'", "'Content Writer'",
       "'Educational Consultant'", 'Teacher', 'Manager', 'Chef', 'Doctor',
       'Lawyer', 'Entrepreneur', 'Pharmacist'], dtype=object)

In [13]:
data['Degree'].unique()

array(['B.Pharm', 'BSc', 'BA', 'BCA', 'M.Tech', 'PhD', "'Class 12'",
       'B.Ed', 'LLB', 'BE', 'M.Ed', 'MSc', 'BHM', 'M.Pharm', 'MCA', 'MA',
       'B.Com', 'MD', 'MBA', 'MBBS', 'M.Com', 'B.Arch', 'LLM', 'B.Tech',
       'BBA', 'ME', 'MHM', 'Others'], dtype=object)

In [14]:
data['Academic Pressure'].unique()

array([5., 2., 3., 4., 1., 0.])

In [15]:
data['Sleep Duration'].unique()

array(["'5-6 hours'", "'Less than 5 hours'", "'7-8 hours'",
       "'More than 8 hours'", 'Others'], dtype=object)

In [16]:
data['Job Satisfaction'].unique()

array([0., 3., 4., 2., 1.])

In [17]:
data['Work/Study Hours'].unique()

array([ 3.,  9.,  4.,  1.,  0., 12.,  2., 11., 10.,  6.,  8.,  5.,  7.])

In [18]:
data['Work Pressure'].unique()

array([0., 5., 2.])

In [19]:
data['Dietary Habits'].unique()

array(['Healthy', 'Moderate', 'Unhealthy', 'Others'], dtype=object)

## Analysis of the Depression Data

**Depression Rate in %**

In [42]:
(data['Depression'].mean() * 100).round(2)

np.float64(58.55)

**How many Males and Females are depressed?**

In [51]:
data.groupby(['Gender'])['Depression'].sum()

Gender
Female    7221
Male      9115
Name: Depression, dtype: int64

**Depression count based on City**

In [52]:
data.groupby(['City'])['Depression'].sum().sort_values(ascending = False).head(10)

City
Kalyan         934
Hyderabad      897
Srinagar       763
Vasai-Virar    739
Thane          673
Kolkata        649
Ludhiana       647
Lucknow        641
Ahmedabad      640
Patna          636
Name: Depression, dtype: int64

**Depression count based on family history of mental illness**

In [43]:
data.groupby(['Mental illness'])['Depression'].count()

Mental illness
No     14398
Yes    13503
Name: Depression, dtype: int64

**Depression count based on suicidal thoughts**

In [45]:
data.groupby(['Suicidal thoughts'])['Depression'].count()

Suicidal thoughts
No     10245
Yes    17656
Name: Depression, dtype: int64

**Sleep Duration based on Profession count**

In [21]:
data.groupby(['Sleep Duration'])['Profession'].count()

Sleep Duration
'5-6 hours'            6183
'7-8 hours'            7346
'Less than 5 hours'    8310
'More than 8 hours'    6044
Others                   18
Name: Profession, dtype: int64

**Sleep Duration based on average Age**

In [22]:
data[data['Depression']==1].groupby(['Sleep Duration'])['Age'].mean().round(0).astype(int)

Sleep Duration
'5-6 hours'            25
'7-8 hours'            25
'Less than 5 hours'    25
'More than 8 hours'    25
Others                 26
Name: Age, dtype: int64

**Professions who are affected by Depression based on average age**

In [24]:
data[data['Depression']==1 ].groupby(['Profession']) [['Age']].mean().round(0).astype(int)

Age
Profession                   
'Civil Engineer'           21
'Content Writer'           30
'Digital Marketer'         24
'Educational Consultant'   32
'UX/UI Designer'           32
Architect                  27
Chef                       26
Doctor                     30
Entrepreneur               21
Lawyer                     23
Manager                    23
Pharmacist                 30
Student                    25
Teacher                    26

**Sleep Duration of the Profession based on average age**

In [25]:
data.groupby(['Sleep Duration','Profession'])[['Age']].mean().round().astype(int)

Age
Sleep Duration      Profession                   
'5-6 hours'         'Civil Engineer'           21
                    'Content Writer'           25
                    'Digital Marketer'         28
                    Architect                  28
                    Student                    26
                    Teacher                    30
'7-8 hours'         'Content Writer'           34
                    'Educational Consultant'   32
                    'UX/UI Designer'           32
                    Architect                  22
                    Chef                       26
                    Pharmacist                 32
                    Student                    26
                    Teacher                    24
'Less than 5 hours' 'Digital Marketer'         21
                    Architect                  28
                    Doctor                     30
                    Entrepreneur               21
                    Student                    26
                    Teacher                    27
'More than 8 hours' 'Digital Marketer'         28
                    Architect                  27
                    Lawyer                     23
                    Manager                    23
                    Pharmacist                 29
                    Student                    26
                    Teacher                    23
Others              Student                    27

In [26]:
# Creating of new column Age Group
def Age_group(x):
  if x <= 18:
    return 'Teen'
  if x <= 25:
    return '18-25'
  if x <=35:
    return '26-35'
  if x <= 45:
    return '36-45'
  else:
    return '50+'
data['Age_group']=data['Age'].apply(Age_group)
data.head()

id  Gender   Age           City Profession  Academic Pressure  \
0   2    Male  33.0  Visakhapatnam    Student                5.0   
1   8  Female  24.0      Bangalore    Student                2.0   
2  26    Male  31.0       Srinagar    Student                3.0   
3  30  Female  28.0       Varanasi    Student                3.0   
4  32  Female  25.0         Jaipur    Student                4.0   

   Work Pressure  CGPA  Study Satisfaction  Job Satisfaction  \
0            0.0  8.97                 2.0               0.0   
1            0.0  5.90                 5.0               0.0   
2            0.0  7.03                 5.0               0.0   
3            0.0  5.59                 2.0               0.0   
4            0.0  8.13                 3.0               0.0   

        Sleep Duration Dietary Habits   Degree Suicidal thoughts  \
0          '5-6 hours'        Healthy  B.Pharm               Yes   
1          '5-6 hours'       Moderate      BSc                No   
2  'Less than 5 hours'        Healthy       BA                No   
3          '7-8 hours'       Moderate      BCA               Yes   
4          '5-6 hours'       Moderate   M.Tech               Yes   

   Work/Study Hours Financial Stress Mental illness  Depression Age_group  
0               3.0              1.0             No           1     26-35  
1               3.0              2.0            Yes           0     18-25  
2               9.0              1.0            Yes           0     26-35  
3               4.0              5.0            Yes           1     26-35  
4               1.0              1.0             No           0     18-25

## Analysing of the Highest depression rate

**Which age facing of the highest and lowest depression rate?**

In [50]:
(data.groupby(['Age'])['Depression'].mean()*100).round(2)

Age
18.0     76.62
19.0     70.51
20.0     70.59
21.0     67.73
22.0     60.43
23.0     63.89
24.0     66.83
25.0     60.65
26.0     57.40
27.0     60.67
28.0     61.32
29.0     56.56
30.0     41.40
31.0     48.07
32.0     51.90
33.0     38.99
34.0     27.38
35.0     20.00
36.0     14.29
37.0      0.00
38.0     25.00
39.0     66.67
41.0    100.00
42.0     50.00
43.0     50.00
44.0      0.00
46.0     50.00
48.0     33.33
49.0      0.00
51.0      0.00
54.0      0.00
56.0      0.00
58.0      0.00
59.0      0.00
Name: Depression, dtype: float64

**Which age group has the highest depression rate?**

In [27]:
(data.groupby(['Age_group']) ['Depression'].mean()*100).round(2).sort_values(ascending = False)

Age_group
Teen     76.62
18-25    66.22
26-35    49.75
36-45    32.14
50+      18.18
Name: Depression, dtype: float64

**Which city has the highest number of depressed people?**

In [28]:
# Top 5 cities of depressed people
data[data['Depression']==1].groupby(['City'])['Depression'].count().sort_values(ascending=False).head(5)

City
Kalyan         934
Hyderabad      897
Srinagar       763
Vasai-Virar    739
Thane          673
Name: Depression, dtype: int64

**Which Profession has the highest number of depression?**

In [29]:
# Top 5 Profession has depression
data[data['Depression']==1].groupby(['Profession'])['Depression'].count().sort_values(ascending = False).head(5)

Profession
Student               16308
Architect                 7
Teacher                   5
Chef                      2
'Digital Marketer'        2
Name: Depression, dtype: int64

**Which degree has the highest number of depression?**

In [30]:
data[data['Depression']==1].groupby(['Degree'])['Depression'].count().sort_values(ascending = False).head(10)

Degree
'Class 12'    4303
B.Ed          1021
B.Arch         871
B.Com          853
BCA            819
MSc            679
B.Tech         655
MCA            559
BSc            523
M.Tech         521
Name: Depression, dtype: int64

**CGPA based on Depression**

In [31]:
data['CGPA_Category']= data['CGPA'].apply(lambda x: 'Low' if x<6 else 'High')
(data.groupby(['CGPA_Category'])['Depression'].mean()*100).round(2)

CGPA_Category
High    59.27
Low     55.56
Name: Depression, dtype: float64

**What is the average Academic pressure and CGPA of students who are having 9+ hours of study hours?**

In [32]:
data[
    (data['Profession']=='Student') &
     (data['Work/Study Hours'] >= 9)] [['Academic Pressure','CGPA']].mean().round(2)

Academic Pressure    3.25
CGPA                 7.68
dtype: float64

**What are the  levels of job satisfaction and financial stress for professional with work pressure?**

In [33]:
data[ (data['Profession']!='Students') &
     (data['Work Pressure'] > 3)] [['Job Satisfaction','Financial Stress']]

Job Satisfaction Financial Stress
4365                4.0              3.0
25746               4.0              4.0

**How many people feeling suicidal thoughts, mental illness due to depression?**

In [35]:
(data.groupby(['Suicidal thoughts','Mental illness'])['Depression'].mean()*100).sort_values(ascending = False).round(2)

Suicidal thoughts  Mental illness
Yes                Yes               81.03
                   No                77.11
No                 Yes               25.22
                   No                21.47
Name: Depression, dtype: float64

**Profession who follows of healthy dietary habits**

In [36]:
(data[data['Dietary Habits']=='Healthy'].groupby(['Profession']) ['Depression'].mean()*100).sort_values(ascending = False).round(2)

Profession
'Civil Engineer'            100.00
'Educational Consultant'    100.00
Teacher                     100.00
Chef                        100.00
Doctor                      100.00
Manager                     100.00
Pharmacist                  100.00
'Digital Marketer'           50.00
Architect                    50.00
Student                      45.33
Name: Depression, dtype: float64